name: Go

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
  
    - name: Run tests and generate coverage report
      run: |
        cd graphql-api
        go get -t ./...
        go test -coverprofile=coverage.out.temp ./...
        cat coverage.out.tmp | grep -v "generated.go" > coverage.out
      #  go tool cover -func=coverage.out

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./graphql-api/coverage.out
