name: Go

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
  
    - name: Run tests and generate coverage report
      run: |

        # run tests in graphql

        cd graphql-api
        go get -t ./...
        go test -coverprofile=graphql_coverage.out.tmp ./...
        cat graphql_coverage.out.tmp | grep -v "generated.go" > graphql_coverage.out

        # run tests in auth-grpc

        cd ..
        cd auth-grpc
        go get -t ./...
        go test -coverprofile=auth-grpc_coverage.out ./...
        # cat coverage.out.tmp | grep -v "generated.go" > graphql_coverage.out
        # go tool cover -func=coverage.out
        
        # move coverage profiles to root
        cd ..
        mv graphql-api/graphql_coverage.out graphql_coverage.out
        mv auth-grpc/auth-grpc_coverage.out auth-grpc_coverage.out

        # Merge the coverage profiles
        cat graphql_coverage.out auth-grpc_coverage.out > coverage.out
        # rm graphql_coverage.out.tmp auth-grpc_coverage.out graphql_coverage.out

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.out
